// THIS FILE IS GENERATED BY THE TOOL, PLEASE DON'T EDIT

using UnityEngine;
using System.Collections;

public partial class ConfigManager : SingletonMono<ConfigManager>
{left}
    private string[] m_ConfigNameList = {left} {config_name_list} {right};
{right}