// THIS FILE IS GENERATED BY THE TOOL, PLEASE DON'T EDIT

using SimpleJSON;

﻿public class ConfigShopRow : ConfigRow
{
	public string Key { get; private set; }
	public int CurrencyType { get; private set; }
	public float Price { get; private set; }
	public int GiveItem { get; private set; }
	public int Num { get; private set; }
	public string Picture { get; private set; }
	public int Desc { get; private set; }

	protected override void Parse(JSONNode node)
	{
		Key = node[1];
		CurrencyType = node[2].AsInt;
		Price = node[3].AsFloat;
		GiveItem = node[4].AsInt;
		Num = node[5].AsInt;
		Picture = node[6];
		Desc = node[7].AsInt;
	}
}

﻿public class ConfigVehicleSortRow : ConfigRow
{
	public int Type { get; private set; }
	public int Chip { get; private set; }
	public int NameId { get; private set; }
	public JSONArray TaskId { get; private set; }
	public string Prefab { get; private set; }
	public string Icon { get; private set; }

	protected override void Parse(JSONNode node)
	{
		Type = node[1].AsInt;
		Chip = node[2].AsInt;
		NameId = node[3].AsInt;
		TaskId = node[4] as JSONArray;
		Prefab = node[5];
		Icon = node[6];
	}
}

﻿public class ConfigPropRow : ConfigRow
{
	public int Name { get; private set; }
	public int Desc { get; private set; }
	public int Value { get; private set; }
	public int Limit { get; private set; }
	public int StoreSwitch { get; private set; }
	public int Cost { get; private set; }
	public int Money { get; private set; }
	public string Tex { get; private set; }

	protected override void Parse(JSONNode node)
	{
		Name = node[1].AsInt;
		Desc = node[2].AsInt;
		Value = node[3].AsInt;
		Limit = node[4].AsInt;
		StoreSwitch = node[5].AsInt;
		Cost = node[6].AsInt;
		Money = node[7].AsInt;
		Tex = node[8];
	}
}

﻿public class ConfigGiftRow : ConfigRow
{
	public int GiftId { get; private set; }
	public int Name { get; private set; }
	public int Type { get; private set; }
	public int Price2 { get; private set; }
	public int Des { get; private set; }
	public string Related { get; private set; }

	protected override void Parse(JSONNode node)
	{
		GiftId = node[1].AsInt;
		Name = node[2].AsInt;
		Type = node[3].AsInt;
		Price2 = node[4].AsInt;
		Des = node[5].AsInt;
		Related = node[6];
	}
}

﻿public class ConfigTaskRow : ConfigRow
{
	public int Type { get; private set; }
	public int PrevTaskId { get; private set; }
	public int NextTaskId { get; private set; }
	public int Value { get; private set; }
	public string Tex { get; private set; }
	public int ItemId { get; private set; }
	public int Num { get; private set; }
	public int Title { get; private set; }
	public int Desc { get; private set; }

	protected override void Parse(JSONNode node)
	{
		Type = node[1].AsInt;
		PrevTaskId = node[2].AsInt;
		NextTaskId = node[3].AsInt;
		Value = node[4].AsInt;
		Tex = node[5];
		ItemId = node[6].AsInt;
		Num = node[7].AsInt;
		Title = node[8].AsInt;
		Desc = node[9].AsInt;
	}
}

﻿public class ConfigGarageRewardRow : ConfigRow
{
	public int AddCup { get; private set; }
	public int Item { get; private set; }
	public int Num { get; private set; }
	public string Tex { get; private set; }

	protected override void Parse(JSONNode node)
	{
		AddCup = node[1].AsInt;
		Item = node[2].AsInt;
		Num = node[3].AsInt;
		Tex = node[4];
	}
}

﻿public class ConfigGaragePagingRow : ConfigRow
{
	public int AddNum { get; private set; }

	protected override void Parse(JSONNode node)
	{
		AddNum = node[1].AsInt;
	}
}

﻿public class ConfigBaseDataRow : ConfigRow
{
	public int Value { get; private set; }

	protected override void Parse(JSONNode node)
	{
		Value = node[1].AsInt;
	}
}

﻿public class ConfigAchievementRow : ConfigRow
{
	public int Type { get; private set; }
	public int VehicleId { get; private set; }
	public int Value { get; private set; }
	public int Cup { get; private set; }
	public int Desc { get; private set; }

	protected override void Parse(JSONNode node)
	{
		Type = node[1].AsInt;
		VehicleId = node[2].AsInt;
		Value = node[3].AsInt;
		Cup = node[4].AsInt;
		Desc = node[5].AsInt;
	}
}

﻿public class ConfigBonusPoolRow : ConfigRow
{
	public int Prop { get; private set; }
	public int Num { get; private set; }
	public string Tex { get; private set; }
	public int GeneralBox { get; private set; }
	public int ExquisiteBox { get; private set; }
	public int LuckBox { get; private set; }

	protected override void Parse(JSONNode node)
	{
		Prop = node[1].AsInt;
		Num = node[2].AsInt;
		Tex = node[3];
		GeneralBox = node[4].AsInt;
		ExquisiteBox = node[5].AsInt;
		LuckBox = node[6].AsInt;
	}
}

﻿public class ConfigVehicleRow : ConfigRow
{
	public int Sort { get; private set; }
	public string Tex { get; private set; }
	public string Color { get; private set; }

	protected override void Parse(JSONNode node)
	{
		Sort = node[1].AsInt;
		Tex = node[2];
		Color = node[3];
	}
}

﻿public class ConfigGoogleplayTaskRow : ConfigRow
{
	public int Type { get; private set; }
	public int Value { get; private set; }
	public string GoogleKey { get; private set; }

	protected override void Parse(JSONNode node)
	{
		Type = node[1].AsInt;
		Value = node[2].AsInt;
		GoogleKey = node[3];
	}
}

