// THIS FILE IS GENERATED BY THE TOOL, PLEASE DON'T EDIT

using UnityEngine;
using System.Collections;

public partial class ConfigManager : SingletonMono<ConfigManager>
{
    private string[] m_ConfigNameList = { "Shop", "VehicleSort", "Prop", "Gift", "Task", "GarageReward", "GaragePaging", "BaseData", "Achievement", "BonusPool", "Vehicle", "GoogleplayTask" };
}